#!/bin/sh

. /home/fraanaalonso/wordpress-5.7.2-0/scripts/setenv.sh
SASL_PATH="/home/fraanaalonso/wordpress-5.7.2-0/common/lib/sasl2"
                export SASL_PATH
exec /home/fraanaalonso/wordpress-5.7.2-0/common/sbin/.saslpasswd2.bin -f "/home/fraanaalonso/wordpress-5.7.2-0/common/etc/sasldb2" "$@"
